#!/bin/bash
# =============================================================================
#  UrrunBerri OS — Install Script
#  Transforms any Debian 12 / Ubuntu 22.04+ PC into a ThinStation-like thin client
#  One config file → boots directly into one connection
#
#  Usage: sudo bash install.sh [OPTIONS]
#    --protocol rdp|vnc|ssh|web   (default: rdp)
#    --host     IP or hostname     (default: 192.168.1.10)
#    --port     port number        (default: 3389)
#    --user     username           (default: Administrateur)
#    --lang     fr|en|es|eu        (default: fr)
#
#  Author: Mathieu Cadi — Openema SARL
# =============================================================================

set -euo pipefail

CYAN='\033[0;36m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BOLD='\033[1m'; NC='\033[0m'

info()    { echo -e "${CYAN}[UrrunBerri OS]${NC} $*"; }
success() { echo -e "${GREEN}[  OK  ]${NC} $*"; }
step()    { echo -e "\n${BOLD}${CYAN}━━━ $* ━━━${NC}\n"; }

# Defaults
PROTOCOL="rdp"; HOST="192.168.1.10"; PORT="3389"
USERNAME="Administrateur"; LANG_CONF="fr"
THIN_USER="thin"; INSTALL_DIR="/opt/urrunberri-os"

while [[ $# -gt 0 ]]; do
  case $1 in
    --protocol) PROTOCOL="$2"; shift 2 ;;
    --host)     HOST="$2";     shift 2 ;;
    --port)     PORT="$2";     shift 2 ;;
    --user)     USERNAME="$2"; shift 2 ;;
    --lang)     LANG_CONF="$2";shift 2 ;;
    *) shift ;;
  esac
done

[[ $EUID -ne 0 ]] && echo "Run as root: sudo bash install.sh" && exit 1

echo -e "${CYAN}"
cat << 'BANNER'
 _   _                      ____                  _ ___  ____
| | | |_ __ _ __ _   _ _ __ | __ )  ___ _ __ _ __(_)/ _ \/ ___|
| | | | '__| '__| | | | '_ \|  _ \ / _ \ '__| '__| | | | \___ \
| |_| | |  | |  | |_| | | | | |_) |  __/ |  | |  | | |_| |___) |
 \___/|_|  |_|   \__,_|_| |_|____/ \___|_|  |_|  |_|\___/|____/

  Thin Client OS — Openema SARL
BANNER
echo -e "${NC}"

info "Protocol  : $PROTOCOL"
info "Host      : $HOST:$PORT"
info "User      : $USERNAME"
info "Language  : $LANG_CONF"
echo ""

export DEBIAN_FRONTEND=noninteractive

step "1/6 — System update"
apt-get update -qq && apt-get upgrade -y -qq
success "System updated"

step "2/6 — Installing packages"
apt-get install -y -qq \
  xorg openbox lightdm \
  freerdp2-x11 tigervnc-viewer openssh-client \
  chromium firefox-esr xterm \
  curl wget unclutter xdotool \
  pulseaudio fonts-dejavu \
  network-manager
success "Packages installed"

step "3/6 — Creating thin user"
id "$THIN_USER" &>/dev/null || useradd -m -s /bin/bash "$THIN_USER"
echo "$THIN_USER:urrunberri" | chpasswd
usermod -aG audio,video,netdev "$THIN_USER"
success "User '$THIN_USER' ready"

step "4/6 — Installing UrrunBerri OS"
mkdir -p "$INSTALL_DIR"/{scripts,splash,config}

# Copy files
cp "$(dirname "$0")/scripts/boot.sh" "$INSTALL_DIR/scripts/"
cp "$(dirname "$0")/client-ui/splash/index.html" "$INSTALL_DIR/splash/"
chmod +x "$INSTALL_DIR/scripts/boot.sh"
success "Files installed to $INSTALL_DIR"

step "5/6 — Configuration"
cat > "/etc/urrunberri-os/config.conf" << EOF
# UrrunBerri OS Configuration
# Generated by install.sh on $(date)
PROTOCOL=$PROTOCOL
HOST=$HOST
PORT=$PORT
USERNAME=$USERNAME
DOMAIN=
RESOLUTION=1920x1080
FULLSCREEN=true
COLOR_DEPTH=32
LANG=$LANG_CONF
RDP_CLIPBOARD=true
RDP_SOUND=false
RDP_FONTS=true
RDP_RECONNECT=true
SHOW_SPLASH=true
SPLASH_DURATION=5
EOF
success "Config written to /etc/urrunberri-os/config.conf"

step "6/6 — Kiosk setup"
# LightDM auto-login
cat > /etc/lightdm/lightdm.conf << EOF
[Seat:*]
autologin-user=$THIN_USER
autologin-user-timeout=0
user-session=openbox
greeter-hide-users=true
EOF

# Openbox autostart
mkdir -p "/home/$THIN_USER/.config/openbox"
cat > "/home/$THIN_USER/.config/openbox/autostart" << EOF
#!/bin/bash
xset s off; xset s noblank; xset -dpms
xsetroot -solid "#0d2233"
unclutter -idle 3 -root &
sleep 2
bash $INSTALL_DIR/scripts/boot.sh
EOF
chmod +x "/home/$THIN_USER/.config/openbox/autostart"
chown -R "$THIN_USER:$THIN_USER" "/home/$THIN_USER/.config"

# Anti-TTY switch
mkdir -p /etc/X11/xorg.conf.d
cat > /etc/X11/xorg.conf.d/99-kiosk.conf << EOF
Section "ServerFlags"
  Option "DontVTSwitch" "true"
  Option "DontZap" "true"
EndSection
EOF

success "Kiosk configured"

echo ""
echo -e "${GREEN}${BOLD}"
echo "╔══════════════════════════════════════════════════════╗"
echo "║    UrrunBerri OS — Installation terminée !          ║"
echo "║    Redémarrez pour démarrer le thin client.          ║"
echo "╚══════════════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""
info "Configuration : /etc/urrunberri-os/config.conf"
info "Pour modifier le serveur cible, éditez ce fichier puis redémarrez."
echo ""
echo -e "${BOLD}  → sudo reboot${NC}"
echo ""
